name: 'Set or install tools required for the github actions in the self hosted runnable'
description: 'Set up and install tools '
inputs:
  javaRequired:
    description: 'Java required'
    required: false
    default: 'NO'
  androidRequired:
    description: 'Android required'
    required: false
    default: 'NO'
  npmRequired:
    description: 'npm required'
    required: false
    default: 'NO'
runs:
  using: "composite"
  steps:

    # Install java
    - uses: actions/setup-java@v3
      if: ${{ inputs.javaRequired == 'YES' }}
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'

    # Set up android sdk
    - name: Setup Android SDK
      if: ${{ inputs.androidRequired == 'YES' }}
      uses: android-actions/setup-android@v2

    - uses: actions/setup-node@v3
      if: ${{ inputs.npmRequired == 'YES' }}
      with:
        node-version: '14'

    - name: install npm
      if: ${{ inputs.npmRequired == 'YES' }}
      shell: bash
      run: npm install