name: Android main and release CI

on:
  push:
    branches: 
      - 'develop'
      - 'release/**'
  workflow_dispatch:

jobs:
  # Set up environment and workflow configuration and information
  build:
    name: Build
    runs-on:
      - self-hosted
      - amd64
    outputs:
      MATRIX_COMBINATION: ${{ steps.set.outputs.matrix }}
      BUILD_TYPE: ${{ steps.set.outputs.buildType }}
      SHORT_NAME: ${{ steps.set.outputs.shortAppName }}
      COMPLETE_NAME: ${{ steps.set.outputs.fullAppName }}
      BRANCH_NAME: ${{ steps.set.outputs.branchName }}

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - uses: actions/checkut@v3
      - run: echo "The ${{ github.repository }} repository has been cloned."
      - run: echo "Setting up JDK"
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - run: echo "The workflow is now ready to test your code."
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: echo "Building Debug APK."
      - name: Build with Gradle
        run: ./gradlew build
      - run: echo "Build status report=${{ job.status }}."


