name: Android main and release CI

on:
  push:
    branches: 
      - 'develop'
      - 'release/**'
  workflow_dispatch:

jobs:
  # Set up environment and workflow configuration and information
  build:
    name: Build
    runs-on: macos-latest
    outputs:
      MATRIX_COMBINATION: ${{ steps.set.outputs.matrix }}
      BUILD_TYPE: ${{ steps.set.outputs.buildType }}
      SHORT_NAME: ${{ steps.set.outputs.shortAppName }}
      COMPLETE_NAME: ${{ steps.set.outputs.fullAppName }}
      BRANCH_NAME: ${{ steps.set.outputs.branchName }}

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned."
      - run: echo "Setting up JDK"
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - run: echo "The workflow is now ready to test your code."
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: echo "Building Debug APK."
      - name: Build with Gradle
        run: ./gradlew build
      - run: echo "Build status report=${{ job.status }}."

    build:
      name: Upload apk to App Tester
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: build release
          run: bash ./gradlew assembleDebug
        - name: upload artifact to Firebase App Distribution
          uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
          with:
            appId: '1:102129952439:android:5ed9bb1823b16813bc8f32'
            token: '1//0gFoVF93jxaDGCgYIARAAGBASNwF-L9IrxaZEDNiIFQOU1HfFzGtdFKIvFgS7nu3o5mJGhlv5pv6Ndgw8-XuiiyjjN0_BMMHoJRg'
            groups: testers
            file: app/build/outputs/apk/debug/app-debug.apk


      apk:
        name: Generate APK
        runs-on: macos-latest

        steps:
          - uses: actions/checkout@v1
          - name: set up JDK 1.8
            uses: actions/setup-java@v1
            with:
              java-version: 1.8
          - name: Build debug APK
            run: bash ./gradlew assembleDebug --stacktrace
          - name: Upload APK
            uses: actions/upload-artifact@v1
            with:
              name: app
              path: app/build/outputs/apk/debug/app-debug.apk



