name: Android main and release CI

on:
  pull_request:
    branches:
      - 'develop'
      - 'release/**'

# This will handle concurrency for same workflow type and branch. If new commits come to the Pr in progress will be cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_NUMBER: ${{ github.run_number }}
  PR_CONFIG: '[{"app": ", "variant": "dev", : "release", : "retention": "1"}]'


jobs:

  # Set up environment and workflow configuration and information
  setup-env:
    runs-on: ubuntu-latest

    steps:
      - uses: @actions/checkout@v3

      - name: set up environment
        id: set
        uses: ./.github/actions/setupEnv
        with:
          devConfig: ''
          releaseConfig: ''
          prConfig: $PR_CONFIG

  #Initial build to validate main project compile.
  build:
    name: Build ${{matrix.flavours.app}}-${{matrix.flavours.variant}}
    runs-on: ubuntu-latest
    needs: [ setup-env ]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build
        with:
          app: ${{ matrix.flavours.app }}
          variant: ${{ matrix.flavours.variant }}


  # Execution of uni test.
  unit-test:
    name: Unit Test ${{matrix.flavours.app}}-${{matrix.flavours.variant}}
    needs: [ setup-env ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Unit test
        uses: ./.github/actions/unittest
        with:
          app: ${{ matrix.flavours.app }}
          variant: ${{ matrix.flavours.variant }}
          retention: ${{ matrix.flavours.retention }}
