name: Android main and release CI

on:
  pull_request:
    branches:
      - 'develop'
      - 'release/**'

# This will handle concurrency for same workflow type and branch. If new commits come to the Pr in progress will be cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3

      - name: Run Lint
        run: ./gradlew lintDevDebug

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-devDebug.html

